CREATE TABLE ITEMS (item_id INT PRIMARY KEY, i_name VARCHAR(30), i_quantity INT);

INSERT INTO ITEMS VALUES (1001, 'Lcd Screens', 24);
INSERT INTO ITEMS VALUES (1005, 'Hard drives', 50);
INSERT INTO ITEMS VALUES (1012, 'Mouse', 30);
INSERT INTO ITEMS VALUES (1123, 'Keyboards', 65);
INSERT INTO ITEMS VALUES (1009, 'CPU', 70);
INSERT INTO ITEMS VALUES (1010, 'RAM', 40);






